services:
  - type: web
    name: lia-crm-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lia-crm-db
          property: connectionString
      - key: NODE_ENV
        value: production
